@echo off
set TMP_PATH=%temp%\x265_build
set X265_PATH=%TMP_PATH%\x265
set SEVENZIP_PATH=C:\Program Files\7-Zip\7z.exe
set ARCHIEVE_PATH_GDRIVE=C:\Users\rigaya\GoogleDrive\x265
set ARCHIEVE_PATH_ONEDRIVE=C:\Users\rigaya\OneDrive\x265
set ARCHIEVE_PATH_DROPBOX=C:\Users\rigaya\DropBox\x265
set ARCHIEVE_LATEST_BUILD_PATH=%ARCHIEVE_PATH_GDRIVE%\latest_build.txt
set GPL_LICENSE_PATH=%ARCHIEVE_PATH_GDRIVE%\txt\gplv2.txt
set VC_OPTIONS=/MP /MT /Ox /Oi /Os /Oy /GT /Gy /GF /fp:fast /D NDEBUG
set VC_LINKER_EXE_OPTIONS=/INCREMENTAL:NO /LARGEADDRESSAWARE /OPT:REF,ICF
set VC_LINKER_MODULE_OPTIONS=/INCREMENTAL:NO
set VC_LINKER_SHARED_OPTIONS=/INCREMENTAL:NO
set VC_LINKER_STATIC_OPTIONS=
set MAIN_BAT_PATH=C:\ProgramEx\Build_x265_main_multilib.bat
set TEST_MOVIE=C:\ProgramEx\Haruiro_OP_Fix4-1-240.y4m
